-- AR Store initial schema

CREATE TABLE users (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                    VARCHAR(64)  NOT NULL,
    email                       VARCHAR(255) NOT NULL,
    password_hash               VARCHAR(255) NOT NULL,
    address                     VARCHAR(500),
    contact                     VARCHAR(64),
    role                        VARCHAR(16)  NOT NULL DEFAULT 'USER',
    verified                    BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token          VARCHAR(255),
    verification_token_expiry   TIMESTAMP,
    created_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token       VARCHAR(255) NOT NULL,
    expiry      TIMESTAMP    NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_prt_token UNIQUE (token)
);

CREATE TABLE collections (
    id         VARCHAR(64)  PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    image_url  VARCHAR(500)
);

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id  VARCHAR(64)    NOT NULL REFERENCES collections (id) ON DELETE CASCADE,
    name           VARCHAR(255)   NOT NULL,
    image_url      VARCHAR(500),
    price          NUMERIC(10, 2) NOT NULL,
    stock          INTEGER        NOT NULL DEFAULT 0,
    rating         INTEGER,
    external_url   VARCHAR(1000),
    featured       BOOLEAN        NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_products_collection_id ON products (collection_id);
CREATE INDEX idx_products_featured ON products (featured);

CREATE TABLE carts (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_carts_user UNIQUE (user_id)
);

CREATE TABLE cart_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id         BIGINT         NOT NULL REFERENCES carts (id) ON DELETE CASCADE,
    product_id      BIGINT         NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    name_snapshot   VARCHAR(255)   NOT NULL,
    price_snapshot  NUMERIC(10, 2) NOT NULL,
    qty             INTEGER        NOT NULL,
    CONSTRAINT uq_cart_items_cart_product UNIQUE (cart_id, product_id)
);

CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL REFERENCES users (id),
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total       NUMERIC(10, 2) NOT NULL,
    status      VARCHAR(32)    NOT NULL DEFAULT 'PAID'
);

CREATE INDEX idx_orders_user_id ON orders (user_id);

CREATE TABLE order_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id      BIGINT         REFERENCES products (id) ON DELETE SET NULL,
    name_snapshot   VARCHAR(255)   NOT NULL,
    price_snapshot  NUMERIC(10, 2) NOT NULL,
    qty             INTEGER        NOT NULL
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
