ALTER TABLE cart_items ADD COLUMN size VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE cart_items ADD COLUMN color VARCHAR(40) NOT NULL DEFAULT '';

ALTER TABLE order_items ADD COLUMN size VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE order_items ADD COLUMN color VARCHAR(40) NOT NULL DEFAULT '';
